export interface Product {
  Handle: string;
  Title: string;
  "Body (HTML)": string;
  Vendor: string;
  "Product Category": string;
  Type: string;
  Tags: string;
  Published: string;
  "Option1 Name": string;
  "Option1 Value": string;
  "Option1 Linked To": string;
  "Option2 Name": string;
  "Option2 Value": string;
  "Option2 Linked To": string;
  "Option3 Name": string;
  "Option3 Value": string;
  "Option3 Linked To": string;
  "Variant SKU": string;
  "Variant Grams": string;
  "Variant Inventory Tracker": string;
  "Variant Inventory Qty": string;
  "Variant Inventory Policy": string;
  "Variant Fulfillment Service": string;
  "Variant Price": string;
  "Variant Compare At Price": string;
  "Variant Requires Shipping": string;
  "Variant Taxable": string;
  "Variant Barcode": string; // This is the UPC field
  "Image Src": string;
  "Image Position": string;
  "Image Alt Text": string;
  "Gift Card": string;
  "SEO Title": string;
  "SEO Description": string;
  "Google Shopping / Google Product Category": string;
  "Google Shopping / Gender": string;
  "Google Shopping / Age Group": string;
  "Google Shopping / MPN": string;
  "Google Shopping / Condition": string;
  "Google Shopping / Custom Product": string;
  "Google Shopping / Custom Label 0": string;
  "Google Shopping / Custom Label 1": string;
  "Google Shopping / Custom Label 2": string;
  "Google Shopping / Custom Label 3": string;
  "Google Shopping / Custom Label 4": string;
  "Checkout Blocks Rule Trigger (product.metafields.checkoutblocks.trigger)": string;
  "Activity (product.metafields.custom.activity)": string;
  "Badges (product.metafields.custom.badges)": string;
  "Buckle Color (product.metafields.custom.buckle_color)": string;
  "Buckle Material  (product.metafields.custom.buckle_material_)": string;
  "Buckle Width (product.metafields.custom.buckle_width)": string;
  "Bundle (product.metafields.custom.bundle)": string;
  "image with text - text (product.metafields.custom.image_with_text_text)": string;
  "Packs (product.metafields.custom.packs)": string;
  "Other (product.metafields.custom.product)": string;
  "Product Category (product.metafields.custom.product_category)": string;
  "Product Feature (product.metafields.custom.product_feature)": string;
  "Season (product.metafields.custom.season)": string;
  "Shipping (product.metafields.custom.shipping)": string;
  "Sock Color (product.metafields.custom.sock_color)": string;
  "Style (product.metafields.custom.sock_height)": string;
  "Buckle Style (product.metafields.custom.style)": string;
  "Video (product.metafields.custom.video)": string;
  "Warranty (product.metafields.custom.warranty)": string;
  "Wool Info (product.metafields.custom.wool_info)": string;
  "Google: Custom Product (product.metafields.mm-google-shopping.custom_product)": string;
  "Product rating count (product.metafields.reviews.rating_count)": string;
  "Hidden Product (product.metafields.seo.hidden)": string;
  "Accessory size (product.metafields.shopify.accessory-size)": string;
  "Activity (product.metafields.shopify.activity)": string;
  "Clothing features (product.metafields.shopify.clothing-features)": string;
  "Color (product.metafields.shopify.color-pattern)": string;
  "Fabric (product.metafields.shopify.fabric)": string;
  "Target gender (product.metafields.shopify.target-gender)": string;
  "Complementary products (product.metafields.shopify--discovery--product_recommendation.complementary_products)": string;
  "Related products (product.metafields.shopify--discovery--product_recommendation.related_products)": string;
  "Related products settings (product.metafields.shopify--discovery--product_recommendation.related_products_display)": string;
  "Search product boosts (product.metafields.shopify--discovery--product_search_boost.queries)": string;
  "Variant Image": string;
  "Variant Weight Unit": string;
  "Variant Tax Code": string;
  "Cost per item": string;
  "Included / United States": string;
  "Price / United States": string;
  "Compare At Price / United States": string;
  "Included / Brunei": string;
  "Price / Brunei": string;
  "Compare At Price / Brunei": string;
  "Included / Canada": string;
  "Price / Canada": string;
  "Compare At Price / Canada": string;
  "Included / International": string;
  "Price / International": string;
  "Compare At Price / International": string;
  Status: string;
}

export interface ProductWithUPC extends Product {
  hasUPC: boolean;
  upcMissing: boolean;
}
